/** Practical, localized guides. Steps and example screenshots describe the current interface. */
module.exports = [
    {
        id: 'disk-space', tags:['discreveal'], image: 'list-view', updated: '2026-10-04', related: ['occupied-space', 'windows-cleanup', 'duplicate-files'],
        en: {
            slug: 'guides/what-is-taking-up-disk-space',
            title: 'What is taking up space on my Windows drive?',
            description: 'Find large folders and files on Windows with DiscReveal. Follow the space usage from your drive down to the files you no longer need.',
            intro: 'Windows says your drive is almost full, but it is not obvious where the space went. Start by finding the largest folders. Then work your way down to the files inside them instead of deleting things at random.',
            result: 'You will know which folders take up the most space and which of your own files are worth reviewing.',
            sections: [
                { title: 'Start with an overview', paragraphs: ['DiscReveal is a free disk space analyzer for Windows 10 and 11 (64-bit). Download discreveal-portable.exe and open it. There is no DiscReveal installer or account to set up. Microsoft Edge WebView2 is required; the app offers an installation link if it is missing.'] },
                { title: 'Find the largest folders, step by step', steps: [
                    ['Choose the drive', 'Select the drive that is running out of space and click “Start scan”. For an external disk or USB drive, choose its drive letter.'],
                    ['Watch the results appear', 'Folder sizes update while the scan runs. You can already browse the results. A folder that is still being scanned may grow as more files are counted.'],
                    ['Follow the biggest folders', 'Use List view to compare sizes and bars. Open a large folder and repeat until you reach files you recognize. In the example below, Videos and Downloads are useful places to investigate.'],
                    ['Find a particular file', 'Use the search field to look for a filename across the scanned tree. Open the charts if you want to explore large files or see how space is split by file type.'],
                    ['Review before removing', 'Wait for the scan to finish, or stop it, before deleting through the app. Check what each file is and whether you still need it. For your own files, the Recycle Bin gives you a chance to restore a mistaken deletion.'],
                ] },
                { title: 'What is worth checking first?', bullets: ['Downloads: old installers, ZIP archives and files you have already copied elsewhere.', 'Videos: recordings and exports can take up a lot of space even when there are only a few files.', 'Backups: confirm that a newer, usable backup exists before removing an older one.', 'Duplicate personal files: use the duplicate finder to check copies rather than judging by name alone.'] },
                { title: 'A large folder is not automatically disposable', paragraphs: ['Windows folders, application data and installed programs can be large because the computer needs them. Uninstall an unwanted application through Windows settings instead of deleting its program folder. DiscReveal helps you see where the space goes; it cannot decide which personal files you still need.', 'Some protected files cannot be read. An inaccessible or incomplete folder may therefore show less than its actual size. Review the final scan results rather than treating a changing number as the final total.'] },
                { title: 'Why is the drive still full after deleting?', paragraphs: ['Files moved to the Recycle Bin still occupy space. Check its contents and empty it when you are sure you no longer need them. If a folder was excluded from the scan, its files will not be part of the results; adjust the exclusions when you need a broader overview.'] },
            ],
            alt: 'Real DiscReveal scan showing Videos and Downloads as the largest folders on a demonstration drive',
            caption: 'DiscReveal’s list view with example data. Folder sizes and bars help you follow the largest files.',
        },
        de: {
            slug: 'de/ratgeber/was-belegt-meine-festplatte',
            title: 'Was belegt meine Festplatte unter Windows?',
            description: 'Finde große Ordner und Dateien unter Windows mit DiscReveal. Sieh Schritt für Schritt, was Platz belegt und welche eigenen Dateien du prüfen solltest.',
            intro: 'Windows meldet eine fast volle Festplatte, aber du weißt nicht, wo der Platz geblieben ist? Finde zuerst die größten Ordner. Schau dann gezielt hinein, statt auf Verdacht Dateien zu löschen.',
            result: 'Danach weißt du, welche Ordner den meisten Platz belegen und welche deiner eigenen Dateien du genauer ansehen solltest.',
            sections: [
                { title: 'Verschaffe dir einen Überblick', paragraphs: ['DiscReveal ist eine kostenlose Speicherplatzanalyse für Windows 10 und 11 mit 64 Bit. Lade discreveal-portable.exe herunter und öffne sie. Eine DiscReveal-Installation oder ein Benutzerkonto brauchst du nicht. Voraussetzung ist Microsoft Edge WebView2; fehlt es, bietet die App einen Installationslink an.'] },
                { title: 'Die größten Ordner finden – Schritt für Schritt', steps: [
                    ['Laufwerk auswählen', 'Wähle das volle Laufwerk und klicke auf „Scan starten“. Für eine externe Festplatte oder einen USB-Stick wählst du den entsprechenden Laufwerksbuchstaben.'],
                    ['Ergebnisse verfolgen', 'Die Ordnergrößen erscheinen und aktualisieren sich während des Scans. Du kannst bereits durch die Ergebnisse navigieren. Wird ein Ordner noch gescannt, kann seine angezeigte Größe weiter steigen.'],
                    ['Die größten Ordner öffnen', 'Vergleiche in der Ansicht „Liste“ die Größen und Balken. Öffne einen großen Ordner und gehe weiter, bis du bei Dateien angekommen bist, die du kennst. Im Beispiel unten lohnt sich zuerst ein Blick in Videos und Downloads.'],
                    ['Gezielt nach Dateien suchen', 'Über das Suchfeld findest du Dateinamen im gesamten gescannten Ordnerbaum. Die Diagramme helfen dir, große Dateien oder die Verteilung nach Dateitypen zu untersuchen.'],
                    ['Vor dem Entfernen prüfen', 'Warte auf das Scan-Ende oder brich den Scan ab, bevor du über die App löschst. Prüfe, wofür die Datei da ist und ob du sie noch brauchst. Für eigene Dateien bietet der Papierkorb eine Möglichkeit, ein versehentliches Löschen rückgängig zu machen.'],
                ] },
                { title: 'Wo lohnt sich der erste Blick?', bullets: ['Downloads: alte Installationsdateien, ZIP-Archive und Dateien, die du bereits an einen anderen Ort kopiert hast.', 'Videos: Aufnahmen und exportierte Videos können schon mit wenigen Dateien viel Platz belegen.', 'Backups: Prüfe vor dem Entfernen einer älteren Sicherung, ob eine neuere, nutzbare Sicherung vorhanden ist.', 'Doppelte eigene Dateien: Lass Kopien mit der Duplikatsuche prüfen, statt allein nach dem Namen zu entscheiden.'] },
                { title: 'Groß bedeutet nicht automatisch überflüssig', paragraphs: ['Windows-Ordner, Anwendungsdaten und installierte Programme können viel Platz belegen, weil dein Computer sie benötigt. Deinstalliere ein unerwünschtes Programm über die Windows-Einstellungen, statt seinen Programmordner zu löschen. DiscReveal zeigt dir die Speicherbelegung; welche persönlichen Dateien du noch brauchst, entscheidest du selbst.', 'Manche geschützten Dateien lassen sich nicht lesen. Ein nicht zugänglicher oder unvollständig gelesener Ordner kann deshalb kleiner angezeigt werden, als er tatsächlich ist. Prüfe das fertige Ergebnis und behandle eine noch laufende Anzeige nicht als endgültige Summe.'] },
                { title: 'Warum ist nach dem Löschen noch kein Platz frei?', paragraphs: ['Dateien im Papierkorb belegen weiterhin Speicherplatz. Prüfe seinen Inhalt und leere ihn, sobald du sicher bist, dass du diese Dateien nicht mehr brauchst. Ausgeschlossene Ordner sind im Scan-Ergebnis nicht enthalten. Passe die Ausschlüsse an, wenn du einen umfassenderen Überblick brauchst.'] },
            ],
            alt: 'Echte DiscReveal-Aufnahme: Videos und Downloads sind die größten Ordner auf einem Laufwerk mit Beispieldateien',
            caption: 'DiscReveal-Listenansicht mit Beispieldaten. Ordnergrößen und Balken führen dich zu den größten Dateien.',
        },
    },
    {
        id: 'duplicate-files', tags:['discreveal'], image: 'duplicates', updated: '2026-10-04', related: ['how-duplicates', 'occupied-space', 'recycle-bin'],
        en: {
            slug: 'guides/remove-duplicate-files',
            title: 'Remove duplicate files while keeping an original',
            description: 'Find duplicate files with DiscReveal, review identical copies and keep an original. Learn how filters and Recycle Bin cleanup work on Windows.',
            intro: 'Photos copied twice, downloaded documents with “copy” in the name, or videos in several folders: duplicates can quietly fill a drive. The important part is confirming that the contents are identical and keeping a usable original.',
            result: 'You will find confirmed duplicate copies, review the retained original and move suitable extra copies to the Recycle Bin.',
            sections: [
                { title: 'A matching name is not enough', paragraphs: ['Two files called holiday.jpg may contain different photos. Two files with different names may contain exactly the same photo. DiscReveal first narrows down candidates by size and a short content check, then compares the complete files byte by byte. Only confirmed identical contents appear as duplicate matches.'] },
                { title: 'Find and review copies, step by step', steps: [
                    ['Open the duplicate finder', 'Choose “Duplicates” in the top menu. You do not need to run a drive scan first.'],
                    ['Choose drives and filters', 'Choose one or more drives. Files below 10 MB are excluded by default to focus on larger copies. Turn off “Exclude small files” if you also want smaller photos or documents included. Under “Search options”, you can set size limits or include or exclude file extensions.'],
                    ['Start the search', 'Click “Start search”. Open a group to review its copies and retained original. Confirmed groups and their potential savings update while files are checked. Result filters let you narrow the list by name or path, size, extension and why the files were grouped.'],
                    ['Check the original and the paths', 'Each group shows which file will stay as the original: the oldest known copy. Read the paths before selecting extra copies. Identical contents do not mean every copy is unnecessary; a project or backup may rely on a particular location.'],
                    ['Select suitable copies', '“Select all suitable” proposes extra copies of personal documents and media and leaves program and system data out of bulk cleanup. Review the selection and remove any copy you still want to keep. The retained original cannot be selected for removal.'],
                    ['Review and clean up', 'Click “Clean up” and review the copies and their retained originals in the confirmation. Cleanup moves the selected copies to the Recycle Bin. Each copy is compared with its original again before removal; changed, missing or no longer identical files are skipped.'],
                ] },
                { title: 'What does the space total mean?', paragraphs: ['Potential savings count extra copies, leaving one original in each group. This is not the total size of every matched file, and it is not a promise that every copy should be removed. The selected size shows the copies you have chosen.', 'Moving files to the Recycle Bin does not immediately release their space. Check the contents and empty it when you are certain you no longer need those files. The potential savings figure is a file-size estimate; the actual free-space change can differ on compressed files or other special file-system layouts.'] },
                { title: 'When a duplicate should stay', bullets: ['A backup is intentionally a second copy. Keep it if it is part of your backup plan.', 'Applications and projects can expect a file at a specific path. Moving a copy may break that reference even though another copy remains.', 'Cloud-synced folders can propagate a deletion to other devices. Check your sync service before removing files there.'] },
                { title: 'Make repeat searches faster when you want to', paragraphs: ['The optional cache can speed up later duplicate searches by recognizing unchanged files. It is off by default and stores file paths, sizes, modification times and short content fingerprints locally in AppData only if you enable it. You can clear it in the app. You do not need the cache for a normal search.'] },
            ],
            alt: 'Real DiscReveal duplicate search showing identical document and photo copies grouped by content',
            caption: 'Duplicate groups in DiscReveal with example data. One original stays in each group; you review the extra copies before cleanup.',
        },
        de: {
            slug: 'de/ratgeber/doppelte-dateien-entfernen',
            title: 'Doppelte Dateien entfernen – ein Original behalten',
            description: 'Finde doppelte Dateien mit DiscReveal, prüfe identische Kopien und behalte ein Original. So funktionieren Filter und Bereinigung über den Papierkorb.',
            intro: 'Fotos zweimal kopiert, Dokumente mit „Kopie“ im Namen oder Videos in mehreren Ordnern: Doppelte Dateien können unbemerkt viel Platz belegen. Entscheidend ist, dass ihr Inhalt wirklich identisch ist und ein nutzbares Original erhalten bleibt.',
            result: 'Du findest bestätigte Duplikate, prüfst das erhaltene Original und verschiebst geeignete überzählige Kopien in den Papierkorb.',
            sections: [
                { title: 'Ein gleicher Name reicht nicht', paragraphs: ['Zwei Dateien namens Urlaub.jpg können unterschiedliche Fotos enthalten. Umgekehrt kann dasselbe Foto unter verschiedenen Namen gespeichert sein. DiscReveal grenzt mögliche Treffer zuerst anhand der Größe und einer kurzen Inhaltsprüfung ein. Anschließend vergleicht es die vollständigen Dateien Byte für Byte. Nur bestätigte identische Inhalte erscheinen als Duplikate.'] },
                { title: 'Kopien finden und prüfen – Schritt für Schritt', steps: [
                    ['Duplikatsuche öffnen', 'Wähle „Duplikate“ im oberen Menü. Ein vorheriger Laufwerksscan ist dafür nicht nötig.'],
                    ['Laufwerke und Filter wählen', 'Wähle ein oder mehrere Laufwerke. Dateien unter 10 MB sind standardmäßig ausgeschlossen, damit sich die Suche auf größere Kopien konzentriert. Schalte „Kleine Dateien ausschließen“ aus, wenn du auch kleinere Fotos oder Dokumente prüfen möchtest. Unter „Suchoptionen“ kannst du Größengrenzen setzen sowie Dateiendungen gezielt ein- oder ausschließen.'],
                    ['Suche starten', 'Klicke auf „Suche starten“. Klappe eine Gruppe auf, um ihre Kopien und das erhaltene Original anzusehen. Bestätigte Gruppen und der potenziell freigebbare Speicher aktualisieren sich während der Prüfung. In der Ergebnisliste kannst du nach Name oder Pfad, Größe, Dateiendung und dem Grund für die Gruppierung filtern.'],
                    ['Original und Speicherorte prüfen', 'Jede Gruppe zeigt, welche Datei als Original erhalten bleibt: die älteste bekannte Kopie. Lies die Pfade, bevor du zusätzliche Kopien markierst. Gleicher Inhalt bedeutet nicht, dass jede Kopie unnötig ist; ein Projekt oder Backup kann einen bestimmten Speicherort benötigen.'],
                    ['Geeignete Kopien markieren', '„Alles Geeignete markieren“ schlägt überzählige Kopien persönlicher Dokumente und Medien vor. Programm- und Systemdaten werden bei der Sammelbereinigung ausgelassen. Prüfe die Auswahl und nimm Kopien heraus, die du behalten möchtest. Das erhaltene Original lässt sich nicht zum Entfernen auswählen.'],
                    ['Auswahl prüfen und bereinigen', 'Klicke auf „Bereinigen“ und prüfe in der Bestätigung die Kopien und ihre erhaltenen Originale. Die ausgewählten Kopien werden in den Papierkorb verschoben. Vor dem Entfernen wird jede Kopie erneut mit ihrem Original verglichen. Veränderte, fehlende oder nicht mehr identische Dateien werden ausgelassen.'],
                ] },
                { title: 'Was bedeutet die angezeigte Speicherersparnis?', paragraphs: ['Der potenziell freigebbare Speicher zählt die zusätzlichen Kopien; ein Original pro Gruppe bleibt außen vor. Die Zahl ist also nicht die Größe aller gefundenen Dateien und bedeutet auch nicht, dass du jede Kopie entfernen solltest. Die Größe der Auswahl bezieht sich auf die von dir markierten Kopien.', 'Das Verschieben in den Papierkorb gibt noch keinen Speicher frei. Prüfe seinen Inhalt und leere ihn, sobald du sicher bist, dass du die Dateien nicht mehr brauchst. Die mögliche Ersparnis ist eine Schätzung anhand der Dateigrößen. Bei komprimierten Dateien oder besonderen Dateisystem-Eigenschaften kann der tatsächlich frei werdende Platz abweichen.'] },
                { title: 'Wann eine Kopie bleiben sollte', bullets: ['Ein Backup ist absichtlich eine zweite Kopie. Behalte es, wenn es zu deiner Sicherungsstrategie gehört.', 'Programme und Projekte erwarten Dateien möglicherweise an einem festen Pfad. Eine entfernte Kopie kann diesen Verweis unterbrechen, obwohl eine andere Kopie vorhanden ist.', 'Bei synchronisierten Cloud-Ordnern kann sich das Löschen auf andere Geräte übertragen. Prüfe vorher, wie dein Synchronisierungsdienst damit umgeht.'] },
                { title: 'Weitere Suchen auf Wunsch beschleunigen', paragraphs: ['Der optionale Cache kann spätere Duplikatsuchen beschleunigen, indem unveränderte Dateien wiedererkannt werden. Er ist standardmäßig ausgeschaltet. Erst wenn du ihn aktivierst, speichert er Dateipfade, Größen, Änderungszeiten und kurze Inhaltskennungen lokal in AppData. Du kannst ihn in der App leeren. Für eine normale Suche brauchst du ihn nicht.'] },
            ],
            alt: 'Echte DiscReveal-Duplikatsuche mit nach identischem Inhalt gruppierten Dokument- und Fotokopien',
            caption: 'Duplikatgruppen in DiscReveal mit Beispieldaten. Pro Gruppe bleibt ein Original; die überzähligen Kopien prüfst du vor dem Bereinigen.',
        },
    },
].concat(require('./knowledge'), require('./update-guide'), require('./storage-guides'));
